services:
  db:
    container_name: postgress-shipment-spring
    image: postgres:latest
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

volumes:
  db:

networks:
  db:
    driver: bridge